### ISSUE TITLE
Liquids not propagating on placing

### ISSUE THREAD

**Issue by e-aakash** [Terasology/SimpleLiquids#4]
How to reproduce:
1. Get some water blocks by the command `give water`
2. Place the water on a plane surface. No flowing of water happens

Possible way to fix:
Create a new event listener similar to [`blockUpdate()`](https://github.com/Terasology/SimpleLiquids/blob/master/src/main/java/org/teraslogy/simpleliquids/block/entity/LiquidEntitySystem.java#L110) to listen to `OnBlockItemPlaced` event

**Comment by Cervator** [comment]
This could be closed as fixed I believe, but I can't close it yet - @skaldarnar halp! 😁
